version: '3.8'

services:
  app:
    image: matiasbasile/varcreative
    container_name: utngis-app
    restart: always
    working_dir: /var/www/
    environment:
      - DATABASE=${DATABASE}
      - PASSWORD_DB=${PASSWORD_DB}
      - SERVER_DB=${SERVER_DB}
      - PROJECT_NAME=${PROJECT_NAME}
      - BASE=${BASE}
      - MAPBOX_KEY=${MAPBOX_KEY}
    volumes:
      - .:/var/www

  nginx:
    image: matiasbasile/nginx:latest
    container_name: utngis-nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    environment:
      - SERVER_DB:"utngis-mysql"

  mysql:
    image: matiasbasile/mysql
    restart: always
    command: mariadbd --sql_mode=""
    container_name: utngis-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD_DB}
      - MYSQL_DATABASE=${DATABASE}
    volumes:
      - utngis-data:/var/lib/mysql

volumes:
  utngis-data:
